INSERT INTO cuentas (numero, nombre, saldo, categoria) VALUES
 (101, 'Efectivo', 0, 'Activos'),
 (111, 'Cuentas por Cobrar', 0, 'Activos'),
 (121, 'Documentos por Cobrar', 0, 'Activos'),
 (141, 'Suministros', 0, 'Activos'),
 (151, 'Mobilario', 0, 'Activos'),
 (171, 'Edifio', 0, 'Activos'),
 (191, 'Terreno', 0, 'Activos'),
 (201, 'Cuentas por Pagar', 0, 'Pasivos'),
 (211, 'Salarios por Pagar', 0, 'Pasivos'),
 (221, 'Intereses por Pagar', 0, 'Pasivos'),
 (231, 'Documentos por Pagar', 0, 'Pasivos'),
 (301, 'Empresa Ejemplo, Capital', 0, 'Capital Contable'),
 (311, 'Empresa Ejemplo, Retiros', 0, 'Capital Contable'),
 (401, 'Ingresos por Servicios', 0, 'Ingresos'),
 (411, 'Ingresos por Intereses', 0, 'Ingresos'),
 (501, 'Gasto por renta, Computadora', 0, 'Gastos'),
 (502, 'Gasto por renta, Oficina', 0, 'Gastos'),
 (505, 'Gasto por Salarios', 0, 'Gastos'),
 (510, 'Gasto por Depreciacion', 0, 'Gastos'),
 (520, 'Gasto por Servicios Generales', 0, 'Gastos'),
 (530, 'Gasto por Publicidad', 0, 'Gastos'),
 (540, 'Gasto por Suministros', 0, 'Gastos')
